/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/
package brickschema.org.schema._1_0_2.BrickFrame;

import brick.global.util.GLOBAL;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import java.math.BigDecimal;
import javax.xml.datatype.XMLGregorianCalendar;
import java.util.Date;


import brickschema.org.schema._1_0_2.BrickFrame.IToken;  
import brickschema.org.schema._1_0_2.BrickFrame.ITagSet;  
import brickschema.org.schema._1_0_2.BrickFrame.Taggable;
	


public  class Token implements IToken {

	IRI newInstance;
	
	public Token(String namespace, String instanceId) {
		super();
		newInstance = GLOBAL.factory.createIRI(namespace, instanceId);
		GLOBAL.model.add(newInstance, RDF.TYPE, GLOBAL.factory.createIRI("https://brickschema.org/schema/1.0.2/BrickFrame#Token"));
	}

	public IRI iri()
	{
		return newInstance;
	}

	
	public void addHastag_Some(IToken parameter)
	{
		GLOBAL.model.add(newInstance, GLOBAL.factory.createIRI("https://brickschema.org/schema/1.0.2/BrickFrame#hasTag"), parameter.iri());
	}
	public void addHastagset_Some(ITagSet parameter)
	{
		GLOBAL.model.add(newInstance, GLOBAL.factory.createIRI("https://brickschema.org/schema/1.0.2/BrickFrame#hasTagSet"), parameter.iri());
	}
	
}
