/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package brickschema.org.schema._1_0_2.BrickFrame;

import java.util.ArrayList;
import java.util.List;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;

import ioinformarics.oss.jackson.module.jsonld.annotation.JsonldId;
import ioinformarics.oss.jackson.module.jsonld.annotation.JsonldProperty;
import ioinformarics.oss.jackson.module.jsonld.annotation.JsonldType;
import ioinformarics.oss.jackson.module.jsonld.annotation.JsonldLink;
import ioinformarics.oss.jackson.module.jsonld.annotation.JsonldPropertyType;

import brick.jsonld.util.RefId;

import brickschema.org.schema._1_0_2.BrickFrame.ITaggable;  
import brickschema.org.schema._1_0_2.BrickFrame.IToken;  
import brickschema.org.schema._1_0_2.BrickFrame.ITagSet;  


public interface IToken extends ITaggable {

	/**
	* @return RefId
	*/
	@JsonIgnore
	public RefId getRefId();
	
	/**
	* addhasTagSome
	* @param IToken
	*/		
	@JsonInclude(Include.NON_EMPTY)
	@JsonldProperty("https://brickschema.org/schema/1.0.2/BrickFrame#hasTag") 
	public void addhasTagSome(IToken parameter);
			
	/**
	* addhasTagSetSome
	* @param ITagSet
	*/		
	@JsonInclude(Include.NON_EMPTY)
	@JsonldProperty("https://brickschema.org/schema/1.0.2/BrickFrame#hasTagSet") 
	public void addhasTagSetSome(ITagSet parameter);
			
	
}
