from rdflib import Namespace, Graph, Literal, RDF, URIRef
from rdfalchemy.rdfSubject import rdfSubject
from rdfalchemy import rdfSingle, rdfMultiple, rdfList

from brick.brickschema.org.schema._1_0_2.Brick.Medium_Temperature_Hot_Water_Discharge_Temperature_Load_Shed_Setpoint import Medium_Temperature_Hot_Water_Discharge_Temperature_Load_Shed_Setpoint
from brick.brickschema.org.schema._1_0_2.Brick.Medium_Temperature_Hot_Water_Supply_Temperature_Load_Shed_Setpoint import Medium_Temperature_Hot_Water_Supply_Temperature_Load_Shed_Setpoint
from brick.brickschema.org.schema._1_0_2.Brick.Load_Shed_Supply_Water_Temperature_Setpoint import Load_Shed_Supply_Water_Temperature_Setpoint


class DemandResponse_Medium_Temperature_Hot_Water_Supply_Temperature_Load_Shed_Setpoint(Medium_Temperature_Hot_Water_Discharge_Temperature_Load_Shed_Setpoint,Medium_Temperature_Hot_Water_Supply_Temperature_Load_Shed_Setpoint,Load_Shed_Supply_Water_Temperature_Setpoint):
    rdf_type = Namespace('https://brickschema.org/schema/1.0.2/Brick#').DemandResponse_Medium_Temperature_Hot_Water_Supply_Temperature_Load_Shed_Setpoint
	
	
