/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package brickschema.org.schema._1_0_2.Brick;

import java.util.ArrayList;
import java.util.List;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;

import ioinformarics.oss.jackson.module.jsonld.annotation.JsonldId;
import ioinformarics.oss.jackson.module.jsonld.annotation.JsonldProperty;
import ioinformarics.oss.jackson.module.jsonld.annotation.JsonldType;
import ioinformarics.oss.jackson.module.jsonld.annotation.JsonldLink;
import ioinformarics.oss.jackson.module.jsonld.annotation.JsonldPropertyType;

import brick.jsonld.util.RefId;

import brickschema.org.schema._1_0_2.Brick.IDischarge_Water_Temperature_Setpoint;  
import brickschema.org.schema._1_0_2.Brick.IMedium_Temperature_Hot_Water;  
import brickschema.org.schema._1_0_2.Brick.IHot_Water_Supply_Temperature_High_Reset_Setpoint;  


public interface IMedium_Temperature_Hot_Water_Discharge_Temperature_High_Reset_Setpoint extends IDischarge_Water_Temperature_Setpoint, IMedium_Temperature_Hot_Water, IHot_Water_Supply_Temperature_High_Reset_Setpoint {

	/**
	* @return RefId
	*/
	@JsonIgnore
	public RefId getRefId();
	
	
}
