/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/
package brickschema.org.schema._1_0_2.Brick;

import brick.global.util.GLOBAL;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import java.math.BigDecimal;
import javax.xml.datatype.XMLGregorianCalendar;
import java.util.Date;


import brickschema.org.schema._1_0_2.Brick.Return_Fan_VFD_Speed_Sensor;
import brickschema.org.schema._1_0_2.Brick.VFD_Speed_Sensor;
import brickschema.org.schema._1_0_2.Brick.Sensor;
import brickschema.org.schema._1_0_2.Brick.Point;
import brickschema.org.schema._1_0_2.BrickFrame.TagSet;
	


public  class FCU_Return_Fan_VFD_Speed_Sensor implements IFCU_Return_Fan_VFD_Speed_Sensor {

	IRI newInstance;
	
	public FCU_Return_Fan_VFD_Speed_Sensor(String namespace, String instanceId) {
		super();
		newInstance = GLOBAL.factory.createIRI(namespace, instanceId);
		GLOBAL.model.add(newInstance, RDF.TYPE, GLOBAL.factory.createIRI("https://brickschema.org/schema/1.0.2/Brick#FCU_Return_Fan_VFD_Speed_Sensor"));
	}

	public IRI iri()
	{
		return newInstance;
	}

	
	
}
