/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package brickschema.org.schema._1_0_2.Brick;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import brickschema.org.schema._1_0_2.Brick.IAHU_Exhaust_Air_Static_Pressure_Sensor;  
import brickschema.org.schema._1_0_2.Brick.ILowest_Exhaust_Air_Static_Pressure_Sensor;  


public interface IAHU_Lowest_Exhaust_Air_Static_Pressure_Sensor extends IAHU_Exhaust_Air_Static_Pressure_Sensor, ILowest_Exhaust_Air_Static_Pressure_Sensor {


	public IRI iri();
			
	
}
