/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package brickschema.org.schema._1_0_2.Brick;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import brickschema.org.schema._1_0_2.Brick.IAHU_Discharge_Air_Temperature_Sensor;  
import brickschema.org.schema._1_0_2.Brick.ICooling_Coil_Discharge_Air_Temperature_Sensor;  
import brickschema.org.schema._1_0_2.Brick.ICooling_Coil_Supply_Air_Temperature_Sensor;  
import brickschema.org.schema._1_0_2.Brick.IAHU_Supply_Air_Temperature_Sensor;  


public interface IAHU_Cooling_Coil_Supply_Air_Temperature_Sensor extends IAHU_Discharge_Air_Temperature_Sensor, ICooling_Coil_Discharge_Air_Temperature_Sensor, ICooling_Coil_Supply_Air_Temperature_Sensor, IAHU_Supply_Air_Temperature_Sensor {


	public IRI iri();
			
	
}
