/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package brickschema.org.schema._1_0_2.Brick;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import brickschema.org.schema._1_0_2.Brick.IHeat_Wheel_Differential_Pressure_Sensor;  
import brickschema.org.schema._1_0_2.Brick.IAHU_Differential_Pressure_Sensor;  


public interface IAHU_Heat_Wheel_Differential_Pressure_Sensor extends IHeat_Wheel_Differential_Pressure_Sensor, IAHU_Differential_Pressure_Sensor {


	public IRI iri();
			
	
}
