/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package brickschema.org.schema._1_0_2.Brick;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import brickschema.org.schema._1_0_2.Brick.IAHU_Supply_Air_Temperature_Sensor;  
import brickschema.org.schema._1_0_2.Brick.IPreheat_Supply_Air_Temperature_Sensor;  
import brickschema.org.schema._1_0_2.Brick.IPreheat_Discharge_Air_Temperature_Sensor;  
import brickschema.org.schema._1_0_2.Brick.IAHU_Discharge_Air_Temperature_Sensor;  


public interface IAHU_Preheat_Supply_Air_Temperature_Sensor extends IAHU_Supply_Air_Temperature_Sensor, IPreheat_Supply_Air_Temperature_Sensor, IPreheat_Discharge_Air_Temperature_Sensor, IAHU_Discharge_Air_Temperature_Sensor {


	public IRI iri();
			
	
}
