/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package brickschema.org.schema._1_0_2.Brick;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import brickschema.org.schema._1_0_2.Brick.IAHU_Discharge_Air_Temperature_Cooling_Setpoint;  
import brickschema.org.schema._1_0_2.Brick.ICooling_Discharge_Air_Temperature_Dead_Band_Setpoint;  
import brickschema.org.schema._1_0_2.Brick.IAHU_Supply_Air_Temperature_Cooling_Setpoint;  
import brickschema.org.schema._1_0_2.Brick.ICooling_Supply_Air_Temperature_Dead_Band_Setpoint;  


public interface IAHU_Cooling_Supply_Air_Temperature_Dead_Band_Setpoint extends IAHU_Discharge_Air_Temperature_Cooling_Setpoint, ICooling_Discharge_Air_Temperature_Dead_Band_Setpoint, IAHU_Supply_Air_Temperature_Cooling_Setpoint, ICooling_Supply_Air_Temperature_Dead_Band_Setpoint {


	public IRI iri();
			
	
}
