/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package brickschema.org.schema._1_0_2.Brick;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import brickschema.org.schema._1_0_2.Brick.IOccupied_Command;  
import brickschema.org.schema._1_0_2.Brick.IOccupancy_Command;  


public interface IAHU_Occupancy_Command extends IOccupied_Command, IOccupancy_Command {


	public IRI iri();
			
	
}
