/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package brickschema.org.schema._1_0_2.Brick;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import brickschema.org.schema._1_0_2.Brick.IDischarge_Fan_Command;  
import brickschema.org.schema._1_0_2.Brick.ISupply_Fan_Command;  


public interface IAHU_Discharge_Fan_Command extends IDischarge_Fan_Command, ISupply_Fan_Command {


	public IRI iri();
			
	
}
