/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package brickschema.org.schema._1_0_2.Brick;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import brickschema.org.schema._1_0_2.Brick.IHeating_Supply_Air_Temperature_Integral_Time_Setpoint;  
import brickschema.org.schema._1_0_2.Brick.IHeating_Discharge_Air_Temperature_Integral_Time_Setpoint;  
import brickschema.org.schema._1_0_2.Brick.IAHU_Supply_Air_Temperature_Heating_Setpoint;  
import brickschema.org.schema._1_0_2.Brick.IAHU_Discharge_Air_Temperature_Heating_Setpoint;  


public interface IAHU_Heating_Supply_Air_Temperature_Integral_Time_Setpoint extends IHeating_Supply_Air_Temperature_Integral_Time_Setpoint, IHeating_Discharge_Air_Temperature_Integral_Time_Setpoint, IAHU_Supply_Air_Temperature_Heating_Setpoint, IAHU_Discharge_Air_Temperature_Heating_Setpoint {


	public IRI iri();
			
	
}
