/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package brickschema.org.schema._1_0_2.Brick;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import brickschema.org.schema._1_0_2.Brick.IAHU_Supply_Air_Temperature_Setpoint;  
import brickschema.org.schema._1_0_2.Brick.IDischarge_Air_Temperature_Setpoint_Increase_Decrease_Step;  
import brickschema.org.schema._1_0_2.Brick.IAHU_Discharge_Air_Temperature_Setpoint;  
import brickschema.org.schema._1_0_2.Brick.ISupply_Air_Temperature_Setpoint_Increase_Decrease_Step;  


public interface IAHU_Supply_Air_Temperature_Setpoint_Increase_Decrease_Step extends IAHU_Supply_Air_Temperature_Setpoint, IDischarge_Air_Temperature_Setpoint_Increase_Decrease_Step, IAHU_Discharge_Air_Temperature_Setpoint, ISupply_Air_Temperature_Setpoint_Increase_Decrease_Step {


	public IRI iri();
			
	
}
