/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package brickschema.org.schema._1_0_2.Brick;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import brickschema.org.schema._1_0_2.Brick.IAHU_Outside_Air_Temperature_Sensor;  
import brickschema.org.schema._1_0_2.Brick.ILow_Outside_Air_Temperature_Enable_Differential_Sensor;  


public interface IAHU_Low_Outside_Air_Temperature_Enable_Differential_Sensor extends IAHU_Outside_Air_Temperature_Sensor, ILow_Outside_Air_Temperature_Enable_Differential_Sensor {


	public IRI iri();
			
	
}
