/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package brickschema.org.schema._1_0_2.Brick;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import brickschema.org.schema._1_0_2.Brick.IProportional_Gain_Setpoint;  
import brickschema.org.schema._1_0_2.Brick.ISupply_Air_Proportional_Gain_Factor;  


public interface IAHU_Supply_Air_Proportional_Gain_Factor extends IProportional_Gain_Setpoint, ISupply_Air_Proportional_Gain_Factor {


	public IRI iri();
			
	
}
