/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package brickschema.org.schema._1_0_2.Brick;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import brickschema.org.schema._1_0_2.Brick.IEconomizer_Discharge_Air_Temperature_Proportional_Band_Setpoint;  
import brickschema.org.schema._1_0_2.Brick.IAHU_Discharge_Air_Temperature_Setpoint;  
import brickschema.org.schema._1_0_2.Brick.IAHU_Supply_Air_Temperature_Setpoint;  
import brickschema.org.schema._1_0_2.Brick.IEconomizer_Supply_Air_Temperature_Proportional_Band_Setpoint;  


public interface IAHU_Economizer_Discharge_Air_Temperature_Proportional_Band_Setpoint extends IEconomizer_Discharge_Air_Temperature_Proportional_Band_Setpoint, IAHU_Discharge_Air_Temperature_Setpoint, IAHU_Supply_Air_Temperature_Setpoint, IEconomizer_Supply_Air_Temperature_Proportional_Band_Setpoint {


	public IRI iri();
			
	
}
