/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package brickschema.org.schema._1_0_2.Brick;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import brickschema.org.schema._1_0_2.Brick.IReturn_Fan_Air_Flow_Sensor;  
import brickschema.org.schema._1_0_2.Brick.IAHU_Return_Air_Flow_Sensor;  


public interface IAHU_Return_Fan_Air_Flow_Sensor extends IReturn_Fan_Air_Flow_Sensor, IAHU_Return_Air_Flow_Sensor {


	public IRI iri();
			
	
}
