/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package brickschema.org.schema._1_0_2.Brick;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import brickschema.org.schema._1_0_2.Brick.IAHU_Overridden_On_Status;  
import brickschema.org.schema._1_0_2.Brick.IExhaust_Fan_Overridden_On_Status;  
import brickschema.org.schema._1_0_2.Brick.IAHU_Exhaust_Fan_Status;  


public interface IAHU_Exhaust_Fan_Overridden_On_Status extends IAHU_Overridden_On_Status, IExhaust_Fan_Overridden_On_Status, IAHU_Exhaust_Fan_Status {


	public IRI iri();
			
	
}
