/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package brickschema.org.schema._1_0_2.Brick;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import brickschema.org.schema._1_0_2.Brick.ISupply_Fan_Start_Stop_Command;  
import brickschema.org.schema._1_0_2.Brick.IAHU_Discharge_Fan_Command;  
import brickschema.org.schema._1_0_2.Brick.IAHU_Supply_Fan_Command;  
import brickschema.org.schema._1_0_2.Brick.IDischarge_Fan_Start_Stop_Command;  


public interface IAHU_Supply_Fan_Start_Stop_Command extends ISupply_Fan_Start_Stop_Command, IAHU_Discharge_Fan_Command, IAHU_Supply_Fan_Command, IDischarge_Fan_Start_Stop_Command {


	public IRI iri();
			
	
}
