/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package brickschema.org.schema._1_0_2.Brick;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import brickschema.org.schema._1_0_2.Brick.IDischarge_Fan_Start_Stop_Status;  
import brickschema.org.schema._1_0_2.Brick.IAHU_Discharge_Fan_Status;  
import brickschema.org.schema._1_0_2.Brick.IAHU_Fan_Start_Stop_Status;  
import brickschema.org.schema._1_0_2.Brick.IAHU_Supply_Fan_Status;  
import brickschema.org.schema._1_0_2.Brick.ISupply_Fan_Start_Stop_Status;  


public interface IAHU_Discharge_Fan_Start_Stop_Status extends IDischarge_Fan_Start_Stop_Status, IAHU_Discharge_Fan_Status, IAHU_Fan_Start_Stop_Status, IAHU_Supply_Fan_Status, ISupply_Fan_Start_Stop_Status {


	public IRI iri();
			
	
}
