/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package brickschema.org.schema._1_0_2.Brick;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import brickschema.org.schema._1_0_2.Brick.IReturn_Air_Temperature_Low_Limit_Alarm;  


public interface IAHU_Return_Air_Temperature_Low_Limit_Alarm extends IReturn_Air_Temperature_Low_Limit_Alarm {


	public IRI iri();
			
	
}
