/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package brickschema.org.schema._1_0_2.Brick;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import brickschema.org.schema._1_0_2.Brick.IAHU_Fan_Start_Stop_Status;  
import brickschema.org.schema._1_0_2.Brick.IAHU_Return_Fan_Status;  
import brickschema.org.schema._1_0_2.Brick.IReturn_Fan_Start_Stop_Status;  


public interface IAHU_Return_Fan_Start_Stop_Status extends IAHU_Fan_Start_Stop_Status, IAHU_Return_Fan_Status, IReturn_Fan_Start_Stop_Status {


	public IRI iri();
			
	
}
