/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package brickschema.org.schema._1_0_2.Brick;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import brickschema.org.schema._1_0_2.Brick.IHeating_Request_Percent_Setpoint;  
import brickschema.org.schema._1_0_2.Brick.IAHU_Heating_Request_Setpoint;  
import brickschema.org.schema._1_0_2.Brick.IDemand_Setpoint;  


public interface IAHU_Heating_Request_Percent_Setpoint extends IHeating_Request_Percent_Setpoint, IAHU_Heating_Request_Setpoint, IDemand_Setpoint {


	public IRI iri();
			
	
}
