/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package brickschema.org.schema._1_0_2.Brick;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import brickschema.org.schema._1_0_2.Brick.IMax_Discharge_Air_Static_Pressure_Setpoint;  
import brickschema.org.schema._1_0_2.Brick.IDischarge_Air_Static_Pressure_Setpoint;  
import brickschema.org.schema._1_0_2.Brick.IMax_Supply_Air_Static_Pressure_Setpoint;  
import brickschema.org.schema._1_0_2.Brick.IAHU_Discharge_Air_Static_Pressure_Setpoint;  
import brickschema.org.schema._1_0_2.Brick.IAHU_Supply_Air_Static_Pressure_Setpoint;  
import brickschema.org.schema._1_0_2.Brick.IAHU_Static_Pressure_Max_Setpoint;  


public interface IAHU_Max_Supply_Air_Static_Pressure_Setpoint extends IMax_Discharge_Air_Static_Pressure_Setpoint, IDischarge_Air_Static_Pressure_Setpoint, IMax_Supply_Air_Static_Pressure_Setpoint, IAHU_Discharge_Air_Static_Pressure_Setpoint, IAHU_Supply_Air_Static_Pressure_Setpoint, IAHU_Static_Pressure_Max_Setpoint {


	public IRI iri();
			
	
}
