/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package brickschema.org.schema._1_0_2.Brick;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import brickschema.org.schema._1_0_2.Brick.IPre_Filter_Status;  
import brickschema.org.schema._1_0_2.Brick.IAHU_Filter_Status;  


public interface IAHU_Pre_Filter_Status extends IPre_Filter_Status, IAHU_Filter_Status {


	public IRI iri();
			
	
}
