/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package brickschema.org.schema._1_0_2.Brick;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import brickschema.org.schema._1_0_2.Brick.ISupply_Fan_VFD_Speed_Status;  
import brickschema.org.schema._1_0_2.Brick.IAHU_VFD_Status;  
import brickschema.org.schema._1_0_2.Brick.IAHU_Supply_Fan_Status;  
import brickschema.org.schema._1_0_2.Brick.IAHU_Discharge_Fan_Status;  
import brickschema.org.schema._1_0_2.Brick.IDischarge_Fan_VFD_Speed_Status;  


public interface IAHU_Discharge_Fan_VFD_Speed_Status extends ISupply_Fan_VFD_Speed_Status, IAHU_VFD_Status, IAHU_Supply_Fan_Status, IAHU_Discharge_Fan_Status, IDischarge_Fan_VFD_Speed_Status {


	public IRI iri();
			
	
}
