/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package brickschema.org.schema._1_0_2.Brick;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import brickschema.org.schema._1_0_2.Brick.IAHU_Exhaust_Air_Static_Pressure_Setpoint;  
import brickschema.org.schema._1_0_2.Brick.IExhaust_Air_Static_Pressure_Dead_Band_Setpoint;  


public interface IAHU_Exhaust_Air_Static_Pressure_Dead_Band_Setpoint extends IAHU_Exhaust_Air_Static_Pressure_Setpoint, IExhaust_Air_Static_Pressure_Dead_Band_Setpoint {


	public IRI iri();
			
	
}
