/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package brickschema.org.schema._1_0_2.Brick;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import brickschema.org.schema._1_0_2.Brick.IMax_Return_Air_CO2_Setpoint;  


public interface IAHU_Max_Return_Air_CO2_Setpoint extends IMax_Return_Air_CO2_Setpoint {


	public IRI iri();
			
	
}
