/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package brickschema.org.schema._1_0_2.Brick;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import brickschema.org.schema._1_0_2.Brick.IExhaust_Air_Stack_Flow_Integral_Time_Setpoint;  
import brickschema.org.schema._1_0_2.Brick.IAHU_Exhaust_Air_Stack_Flow_Setpoint;  


public interface IAHU_Exhaust_Air_Stack_Flow_Integral_Time_Setpoint extends IExhaust_Air_Stack_Flow_Integral_Time_Setpoint, IAHU_Exhaust_Air_Stack_Flow_Setpoint {


	public IRI iri();
			
	
}
