/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package brickschema.org.schema._1_0_2.Brick;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import brickschema.org.schema._1_0_2.Brick.ITemperature_Low;  
import brickschema.org.schema._1_0_2.Brick.IAir_Temperature;  
import brickschema.org.schema._1_0_2.Brick.ILow_Temperature;  


public interface IAir_Temperature_Low_Reset extends ITemperature_Low, IAir_Temperature, ILow_Temperature {


	public IRI iri();
			
	
}
