/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package brickschema.org.schema._1_0_2.Brick;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import brickschema.org.schema._1_0_2.Brick.IChilled_Water_Differential_Pressure;  
import brickschema.org.schema._1_0_2.Brick.IChilled_Water_Pump;  


public interface IChilled_Water_Pump_Differential_Pressure_Integration_Time extends IChilled_Water_Differential_Pressure, IChilled_Water_Pump {


	public IRI iri();
			
	
}
