/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package brickschema.org.schema._1_0_2.Brick;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import brickschema.org.schema._1_0_2.Brick.IStart_Stop_Status;  
import brickschema.org.schema._1_0_2.Brick.IOn_Off_Status;  


public interface IChiller_On_Off_Status extends IStart_Stop_Status, IOn_Off_Status {


	public IRI iri();
			
	
}
