/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package brickschema.org.schema._1_0_2.Brick;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import brickschema.org.schema._1_0_2.Brick.IChilled_Water_Differential_Pressure_Setpoint;  
import brickschema.org.schema._1_0_2.Brick.IDifferential_Pressure_Integral_Time_Setpoint;  


public interface IChilled_Water_Pump_Differential_Pressure_Integration_Time_Setpoint extends IChilled_Water_Differential_Pressure_Setpoint, IDifferential_Pressure_Integral_Time_Setpoint {


	public IRI iri();
			
	
}
