/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package brickschema.org.schema._1_0_2.Brick;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import brickschema.org.schema._1_0_2.Brick.IChilled_Water_Pump;  
import brickschema.org.schema._1_0_2.Brick.IPump_Start_Stop;  


public interface IChilled_Water_Pump_Start_Stop extends IChilled_Water_Pump, IPump_Start_Stop {


	public IRI iri();
			
	
}
