/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package brickschema.org.schema._1_0_2.Brick;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import brickschema.org.schema._1_0_2.Brick.IChilled_Water;  
import brickschema.org.schema._1_0_2.Brick.ISupply_Water_Flow_Sensor;  


public interface IChilled_Water_Supply_Flow_Sensor extends IChilled_Water, ISupply_Water_Flow_Sensor {


	public IRI iri();
			
	
}
