/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package brickschema.org.schema._1_0_2.Brick;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import brickschema.org.schema._1_0_2.Brick.IChilled_Water;  
import brickschema.org.schema._1_0_2.Brick.ISystem_Enable;  


public interface IChilled_Water_System_Enable extends IChilled_Water, ISystem_Enable {


	public IRI iri();
			
	
}
