/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package brickschema.org.schema._1_0_2.Brick;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import brickschema.org.schema._1_0_2.Brick.IChilled_Water;  
import brickschema.org.schema._1_0_2.Brick.IDifferential_Temperature_Sensor;  


public interface IChilled_Water_Temperature_Differential_Sensor extends IChilled_Water, IDifferential_Temperature_Sensor {


	public IRI iri();
			
	
}
