/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package brickschema.org.schema._1_0_2.Brick;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import brickschema.org.schema._1_0_2.Brick.ISupply_Air_Temperature_Cooling_Setpoint;  
import brickschema.org.schema._1_0_2.Brick.IProportional_Band_Setpoint;  
import brickschema.org.schema._1_0_2.Brick.IDischarge_Air_Temperature_Cooling_Setpoint;  


public interface ICooling_Supply_Air_Temperature_Proportional_Band_Setpoint extends ISupply_Air_Temperature_Cooling_Setpoint, IProportional_Band_Setpoint, IDischarge_Air_Temperature_Cooling_Setpoint {


	public IRI iri();
			
	
}
