/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package brickschema.org.schema._1_0_2.Brick;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import brickschema.org.schema._1_0_2.Brick.ISupply_Air_Flow;  
import brickschema.org.schema._1_0_2.Brick.IMin_Air_Flow;  
import brickschema.org.schema._1_0_2.Brick.ICooling;  


public interface ICooling_Min_Supply_Air_Flow extends ISupply_Air_Flow, IMin_Air_Flow, ICooling {


	public IRI iri();
			
	
}
