/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package brickschema.org.schema._1_0_2.Brick;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import brickschema.org.schema._1_0_2.Brick.IIntegral_Time_Setpoint;  
import brickschema.org.schema._1_0_2.Brick.IDischarge_Air_Temperature_Cooling_Setpoint;  
import brickschema.org.schema._1_0_2.Brick.ISupply_Air_Temperature_Cooling_Setpoint;  


public interface ICooling_Discharge_Air_Temperature_Integral_Time_Setpoint extends IIntegral_Time_Setpoint, IDischarge_Air_Temperature_Cooling_Setpoint, ISupply_Air_Temperature_Cooling_Setpoint {


	public IRI iri();
			
	
}
