/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package brickschema.org.schema._1_0_2.Brick;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import brickschema.org.schema._1_0_2.Brick.IPump_Start_Stop_Command;  
import brickschema.org.schema._1_0_2.Brick.ICRAC_Start_Stop_Command;  


public interface ICRAC_Pump_Start_Stop_Command extends IPump_Start_Stop_Command, ICRAC_Start_Stop_Command {


	public IRI iri();
			
	
}
