/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package brickschema.org.schema._1_0_2.Brick;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import brickschema.org.schema._1_0_2.Brick.ICRAC_High_Humidity_Alarm;  
import brickschema.org.schema._1_0_2.Brick.ICRAC_Humidity_Setpoint;  
import brickschema.org.schema._1_0_2.Brick.IHigh_Humidity_Alarm_Setpoint;  


public interface ICRAC_High_Humidity_Alarm_Setpoint extends ICRAC_High_Humidity_Alarm, ICRAC_Humidity_Setpoint, IHigh_Humidity_Alarm_Setpoint {


	public IRI iri();
			
	
}
