/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package brickschema.org.schema._1_0_2.Brick;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import brickschema.org.schema._1_0_2.Brick.ICRAC_Humidity_Sensor;  
import brickschema.org.schema._1_0_2.Brick.IZone_Humidity_Sensor;  


public interface ICRAC_Zone_Humidity_Sensor extends ICRAC_Humidity_Sensor, IZone_Humidity_Sensor {


	public IRI iri();
			
	
}
