/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package brickschema.org.schema._1_0_2.Brick;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import brickschema.org.schema._1_0_2.Brick.ICRAC_Low_Temperature_Alarm;  
import brickschema.org.schema._1_0_2.Brick.ICRAC_Temperature_Setpoint;  
import brickschema.org.schema._1_0_2.Brick.ILow_Temperature_Alarm_Setpoint;  


public interface ICRAC_Low_Temperature_Alarm_Setpoint extends ICRAC_Low_Temperature_Alarm, ICRAC_Temperature_Setpoint, ILow_Temperature_Alarm_Setpoint {


	public IRI iri();
			
	
}
