/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package brickschema.org.schema._1_0_2.Brick;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import brickschema.org.schema._1_0_2.Brick.ICRAC_Standby_Unit_On_Off_Status;  
import brickschema.org.schema._1_0_2.Brick.IStandby_Glycool_Unit_On_Off_Status;  


public interface ICRAC_Standby_Glycool_Unit_On_Off_Status extends ICRAC_Standby_Unit_On_Off_Status, IStandby_Glycool_Unit_On_Off_Status {


	public IRI iri();
			
	
}
