/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package brickschema.org.schema._1_0_2.Brick;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import brickschema.org.schema._1_0_2.Brick.IHigh_Head_Pressure_Alarm;  


public interface ICRAC_High_Head_Pressure_Alarm extends IHigh_Head_Pressure_Alarm {


	public IRI iri();
			
	
}
