/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package brickschema.org.schema._1_0_2.Brick;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import brickschema.org.schema._1_0_2.Brick.IEmergency_Power_Off_Activated_By_High_Temperature_Status;  


public interface ICRAC_Emergency_Power_Off_Activated_By_High_Temperature_Status extends IEmergency_Power_Off_Activated_By_High_Temperature_Status {


	public IRI iri();
			
	
}
