/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package brickschema.org.schema._1_0_2.Brick;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import brickschema.org.schema._1_0_2.Brick.IHumidifier_Panel_No_Water_Alarm;  
import brickschema.org.schema._1_0_2.Brick.ICRAC_Humidifier_Alarm;  


public interface ICRAC_Humidifier_Panel_No_Water_Alarm extends IHumidifier_Panel_No_Water_Alarm, ICRAC_Humidifier_Alarm {


	public IRI iri();
			
	
}
