/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package brickschema.org.schema._1_0_2.Brick;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import brickschema.org.schema._1_0_2.Brick.ICRAC_On_Off_Status;  
import brickschema.org.schema._1_0_2.Brick.ILocally_On_Off_Status;  


public interface ICRAC_Locally_On_Off_Status extends ICRAC_On_Off_Status, ILocally_On_Off_Status {


	public IRI iri();
			
	
}
