/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package brickschema.org.schema._1_0_2.Brick;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import brickschema.org.schema._1_0_2.Brick.ICRAC_Power_Loss_Alarm;  
import brickschema.org.schema._1_0_2.Brick.IEmergency_Power_Loss_Alarm;  


public interface ICRAC_Emergency_Power_Loss_Alarm extends ICRAC_Power_Loss_Alarm, IEmergency_Power_Loss_Alarm {


	public IRI iri();
			
	
}
