/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package brickschema.org.schema._1_0_2.Brick;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import brickschema.org.schema._1_0_2.Brick.ICWS_Chilled_Water_Differential_Pressure_Setpoint;  
import brickschema.org.schema._1_0_2.Brick.IChilled_Water_Differential_Pressure_Increase_Decrease_Step_Setpoint;  


public interface ICWS_Chilled_Water_Differential_Pressure_Increase_Decrease_Step_Setpoint extends ICWS_Chilled_Water_Differential_Pressure_Setpoint, IChilled_Water_Differential_Pressure_Increase_Decrease_Step_Setpoint {


	public IRI iri();
			
	
}
