/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package brickschema.org.schema._1_0_2.Brick;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import brickschema.org.schema._1_0_2.Brick.IChilled_Water_Pump_Start_Stop_Command;  
import brickschema.org.schema._1_0_2.Brick.ICWS_Chilled_Water_Pump_Command;  


public interface ICWS_Chilled_Water_Pump_Start_Stop_Command extends IChilled_Water_Pump_Start_Stop_Command, ICWS_Chilled_Water_Pump_Command {


	public IRI iri();
			
	
}
