/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package brickschema.org.schema._1_0_2.Brick;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import brickschema.org.schema._1_0_2.Brick.IMedium_Temperature_Hot_Water_Discharge_Temperature_Load_Shed_Setpoint;  
import brickschema.org.schema._1_0_2.Brick.IMedium_Temperature_Hot_Water_Supply_Temperature_Load_Shed_Setpoint;  
import brickschema.org.schema._1_0_2.Brick.ILoad_Shed_Supply_Water_Temperature_Setpoint;  


public interface IDemandResponse_Medium_Temperature_Hot_Water_Supply_Temperature_Load_Shed_Setpoint extends IMedium_Temperature_Hot_Water_Discharge_Temperature_Load_Shed_Setpoint, IMedium_Temperature_Hot_Water_Supply_Temperature_Load_Shed_Setpoint, ILoad_Shed_Supply_Water_Temperature_Setpoint {


	public IRI iri();
			
	
}
