/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package brickschema.org.schema._1_0_2.Brick;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import brickschema.org.schema._1_0_2.Brick.IZone_Standby_Load_Shed_Command;  
import brickschema.org.schema._1_0_2.Brick.IDemandResponse_Standby_Load_Shed_Command;  


public interface IDemandResponse_Zone_Standby_Load_Shed_Command extends IZone_Standby_Load_Shed_Command, IDemandResponse_Standby_Load_Shed_Command {


	public IRI iri();
			
	
}
