/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package brickschema.org.schema._1_0_2.Brick;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import brickschema.org.schema._1_0_2.Brick.ISupply_Air;  
import brickschema.org.schema._1_0_2.Brick.IStatic_Pressure_Setpoint;  
import brickschema.org.schema._1_0_2.Brick.IDischarge_Air;  


public interface IDischarge_Air_Static_Pressure_Setpoint extends ISupply_Air, IStatic_Pressure_Setpoint, IDischarge_Air {


	public IRI iri();
			
	
}
