/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package brickschema.org.schema._1_0_2.Brick;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import brickschema.org.schema._1_0_2.Brick.IVelocity_Pressure_Sensor;  
import brickschema.org.schema._1_0_2.Brick.ISupply_Air;  
import brickschema.org.schema._1_0_2.Brick.IDischarge_Air;  


public interface IDischarge_Air_Velocity_Pressure_Sensor extends IVelocity_Pressure_Sensor, ISupply_Air, IDischarge_Air {


	public IRI iri();
			
	
}
