/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package brickschema.org.schema._1_0_2.Brick;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import brickschema.org.schema._1_0_2.Brick.IDischarge_Air;  
import brickschema.org.schema._1_0_2.Brick.IStatic_Pressure;  


public interface IDischarge_Air_Static_Pressure extends IDischarge_Air, IStatic_Pressure {


	public IRI iri();
			
	
}
