/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package brickschema.org.schema._1_0_2.Brick;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import brickschema.org.schema._1_0_2.Brick.ITemperature_High;  
import brickschema.org.schema._1_0_2.Brick.IHigh_Temperature;  
import brickschema.org.schema._1_0_2.Brick.IDischarge_Air_Temperature;  


public interface IDischarge_Air_Temperature_High_Limit extends ITemperature_High, IHigh_Temperature, IDischarge_Air_Temperature {


	public IRI iri();
			
	
}
