/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package brickschema.org.schema._1_0_2.Brick;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import brickschema.org.schema._1_0_2.Brick.ISupply_Air;  
import brickschema.org.schema._1_0_2.Brick.IHumidity_Sensor;  
import brickschema.org.schema._1_0_2.Brick.IDischarge_Air;  


public interface IDischarge_Air_Humidity_Sensor extends ISupply_Air, IHumidity_Sensor, IDischarge_Air {


	public IRI iri();
			
	
}
