/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package brickschema.org.schema._1_0_2.Brick;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import brickschema.org.schema._1_0_2.Brick.ISystem;  
import brickschema.org.schema._1_0_2.Brick.IAir_Temperature;  


public interface IDisable_Hot_Water_System_Air_Temperature extends ISystem, IAir_Temperature {


	public IRI iri();
			
	
}
