/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package brickschema.org.schema._1_0_2.Brick;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import brickschema.org.schema._1_0_2.Brick.IStart_Stop;  
import brickschema.org.schema._1_0_2.Brick.IDomestic_Hot_Water;  
import brickschema.org.schema._1_0_2.Brick.ISystem;  


public interface IDomestic_Hot_Water_System_Start_Stop extends IStart_Stop, IDomestic_Hot_Water, ISystem {


	public IRI iri();
			
	
}
