/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package brickschema.org.schema._1_0_2.Brick;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import brickschema.org.schema._1_0_2.Brick.IHeating_Valve;  
import brickschema.org.schema._1_0_2.Brick.IDomestic_Hot_Water;  


public interface IDomestic_Hot_Water_Valve extends IHeating_Valve, IDomestic_Hot_Water {


	public IRI iri();
			
	
}
