/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package brickschema.org.schema._1_0_2.Brick;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import brickschema.org.schema._1_0_2.Brick.IEconomizer;  
import brickschema.org.schema._1_0_2.Brick.IDischarge_Air_Temperature;  


public interface IEconomizer_Discharge_Air_Temperature_Proportional_Band extends IEconomizer, IDischarge_Air_Temperature {


	public IRI iri();
			
	
}
