/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package brickschema.org.schema._1_0_2.Brick;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import brickschema.org.schema._1_0_2.Brick.ISystem;  
import brickschema.org.schema._1_0_2.Brick.IEmergency_Power_Off;  


public interface IEmergency_Power_Off_Activated_By_Leak_Detection_System extends ISystem, IEmergency_Power_Off {


	public IRI iri();
			
	
}
