/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package brickschema.org.schema._1_0_2.Brick;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import brickschema.org.schema._1_0_2.Brick.IEmergency_Power_Off_Enable;  
import brickschema.org.schema._1_0_2.Brick.ISystem_Enable;  


public interface IEmergency_Power_Off_System_Enable extends IEmergency_Power_Off_Enable, ISystem_Enable {


	public IRI iri();
			
	
}
