/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package brickschema.org.schema._1_0_2.Brick;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import brickschema.org.schema._1_0_2.Brick.IOutside_Air;  
import brickschema.org.schema._1_0_2.Brick.ITemperature_Setpoint;  
import brickschema.org.schema._1_0_2.Brick.IHot_Water;  


public interface IEnable_Hot_Water_System_Outside_Air_Temperature_Setpoint extends IOutside_Air, ITemperature_Setpoint, IHot_Water {


	public IRI iri();
			
	
}
