/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package brickschema.org.schema._1_0_2.Brick;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import brickschema.org.schema._1_0_2.Brick.IExhaust_Fan_Off;  
import brickschema.org.schema._1_0_2.Brick.IOverridden_Off;  


public interface IExhaust_Fan_Overridden_Off extends IExhaust_Fan_Off, IOverridden_Off {


	public IRI iri();
			
	
}
