/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package brickschema.org.schema._1_0_2.Brick;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import brickschema.org.schema._1_0_2.Brick.ISystem_Enable_Command;  
import brickschema.org.schema._1_0_2.Brick.IExhaust_Fan_Enable_Command;  


public interface IExhaust_Fan_System_Enable_Command extends ISystem_Enable_Command, IExhaust_Fan_Enable_Command {


	public IRI iri();
			
	
}
