/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package brickschema.org.schema._1_0_2.Brick;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import brickschema.org.schema._1_0_2.Brick.IExhaust_Fan;  
import brickschema.org.schema._1_0_2.Brick.IExhaust_Air;  


public interface IExhaust_Fan_Air_Flow extends IExhaust_Fan, IExhaust_Air {


	public IRI iri();
			
	
}
