/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package brickschema.org.schema._1_0_2.Brick;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import brickschema.org.schema._1_0_2.Brick.IZone_Air_Temperature_Sensor;  
import brickschema.org.schema._1_0_2.Brick.IFCU_Zone_Temperature_Sensor;  


public interface IFCU_Zone_Air_Temperature_Sensor extends IZone_Air_Temperature_Sensor, IFCU_Zone_Temperature_Sensor {


	public IRI iri();
			
	
}
