/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package brickschema.org.schema._1_0_2.Brick;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import brickschema.org.schema._1_0_2.Brick.ISupply_Air_Temperature_Cooling_Setpoint;  
import brickschema.org.schema._1_0_2.Brick.IFCU_Discharge_Air_Temperature_Setpoint;  
import brickschema.org.schema._1_0_2.Brick.IDischarge_Air_Temperature_Cooling_Setpoint;  
import brickschema.org.schema._1_0_2.Brick.IFCU_Supply_Air_Temperature_Setpoint;  


public interface IFCU_Discharge_Air_Temperature_Cooling_Setpoint extends ISupply_Air_Temperature_Cooling_Setpoint, IFCU_Discharge_Air_Temperature_Setpoint, IDischarge_Air_Temperature_Cooling_Setpoint, IFCU_Supply_Air_Temperature_Setpoint {


	public IRI iri();
			
	
}
