/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package brickschema.org.schema._1_0_2.Brick;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import brickschema.org.schema._1_0_2.Brick.IFCU_VFD_Speed_Command;  
import brickschema.org.schema._1_0_2.Brick.ISupply_Fan_VFD_Speed_Command;  
import brickschema.org.schema._1_0_2.Brick.IDischarge_Fan_VFD_Speed_Command;  


public interface IFCU_Supply_Fan_VFD_Speed_Command extends IFCU_VFD_Speed_Command, ISupply_Fan_VFD_Speed_Command, IDischarge_Fan_VFD_Speed_Command {


	public IRI iri();
			
	
}
