/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package brickschema.org.schema._1_0_2.Brick;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import brickschema.org.schema._1_0_2.Brick.IFire_Control_Panel_Command;  


public interface IFire_Control_Panel_On_Command extends IFire_Control_Panel_Command {


	public IRI iri();
			
	
}
