/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package brickschema.org.schema._1_0_2.Brick;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import brickschema.org.schema._1_0_2.Brick.IAHU_Off_Status_LED;  
import brickschema.org.schema._1_0_2.Brick.IFire_Control_Panel_LED_Status;  


public interface IFire_Control_Panel_AHU_Off_Status_LED extends IAHU_Off_Status_LED, IFire_Control_Panel_LED_Status {


	public IRI iri();
			
	
}
