/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package brickschema.org.schema._1_0_2.Brick;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import brickschema.org.schema._1_0_2.Brick.IFreeze;  
import brickschema.org.schema._1_0_2.Brick.ITemperature_Low;  
import brickschema.org.schema._1_0_2.Brick.ILow_Temperature;  


public interface IFreeze_Protect_Temperature_Low_Limit extends IFreeze, ITemperature_Low, ILow_Temperature {


	public IRI iri();
			
	
}
