/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package brickschema.org.schema._1_0_2.Brick;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import brickschema.org.schema._1_0_2.Brick.IEmergency_Push_Button_Status;  


public interface IFume_Hood_Emergency_Push_Button_Status extends IEmergency_Push_Button_Status {


	public IRI iri();
			
	
}
