/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package brickschema.org.schema._1_0_2.Brick;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import brickschema.org.schema._1_0_2.Brick.IDischarge_Air;  
import brickschema.org.schema._1_0_2.Brick.IHeating;  


public interface IHeating_Discharge_Air_Flow extends IDischarge_Air, IHeating {


	public IRI iri();
			
	
}
