/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package brickschema.org.schema._1_0_2.Brick;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import brickschema.org.schema._1_0_2.Brick.IHeat_Exchanger_Discharge_Water_Temperature_Setpoint;  
import brickschema.org.schema._1_0_2.Brick.ISupply_Water_Temperature_Integral_Time_Setpoint;  
import brickschema.org.schema._1_0_2.Brick.IHeat_Exchanger_Supply_Water_Temperature_Setpoint;  


public interface IHeat_Exchanger_Supply_Water_Temperature_Integral_Time_Setpoint extends IHeat_Exchanger_Discharge_Water_Temperature_Setpoint, ISupply_Water_Temperature_Integral_Time_Setpoint, IHeat_Exchanger_Supply_Water_Temperature_Setpoint {


	public IRI iri();
			
	
}
