/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package brickschema.org.schema._1_0_2.Brick;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import brickschema.org.schema._1_0_2.Brick.IHot_Water;  
import brickschema.org.schema._1_0_2.Brick.IEntering_Water_Temperature_Sensor;  


public interface IHot_Water_Coil_Entering_Temperature_Sensor extends IHot_Water, IEntering_Water_Temperature_Sensor {


	public IRI iri();
			
	
}
