/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package brickschema.org.schema._1_0_2.Brick;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import brickschema.org.schema._1_0_2.Brick.IDifferential_Pressure_Dead_Band_Setpoint;  
import brickschema.org.schema._1_0_2.Brick.IHot_Water_Differential_Pressure_Setpoint;  


public interface IHot_Water_Differential_Pressure_Dead_Band_Setpoint extends IDifferential_Pressure_Dead_Band_Setpoint, IHot_Water_Differential_Pressure_Setpoint {


	public IRI iri();
			
	
}
