/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package brickschema.org.schema._1_0_2.Brick;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import brickschema.org.schema._1_0_2.Brick.ITolerance_Setpoint;  
import brickschema.org.schema._1_0_2.Brick.IHumidity_Setpoint;  


public interface IHumidity_Tolerance_Setpoint extends ITolerance_Setpoint, IHumidity_Setpoint {


	public IRI iri();
			
	
}
