/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package brickschema.org.schema._1_0_2.Brick;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import brickschema.org.schema._1_0_2.Brick.IDischarge_Air_Flow_Sensor;  
import brickschema.org.schema._1_0_2.Brick.IAverage_Supply_Air_Flow_Sensor;  
import brickschema.org.schema._1_0_2.Brick.IAverage_Discharge_Air_Flow_Sensor;  


public interface IHVAC_Average_Discharge_Air_Flow_Sensor extends IDischarge_Air_Flow_Sensor, IAverage_Supply_Air_Flow_Sensor, IAverage_Discharge_Air_Flow_Sensor {


	public IRI iri();
			
	
}
