/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package brickschema.org.schema._1_0_2.Brick;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import brickschema.org.schema._1_0_2.Brick.IHighest_Zone_Cooling_Command;  


public interface IHVAC_Highest_Zone_Cooling_Command extends IHighest_Zone_Cooling_Command {


	public IRI iri();
			
	
}
