/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package brickschema.org.schema._1_0_2.Brick;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import brickschema.org.schema._1_0_2.Brick.IColdest_Zone_Temperature_Sensor;  
import brickschema.org.schema._1_0_2.Brick.ILowest_Zone_Temperature_Sensor;  


public interface IHVAC_Lowest_Zone_Temperature_Sensor extends IColdest_Zone_Temperature_Sensor, ILowest_Zone_Temperature_Sensor {


	public IRI iri();
			
	
}
