/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package brickschema.org.schema._1_0_2.Brick;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import brickschema.org.schema._1_0_2.Brick.ISupply_Water_Temperature_Sensor;  
import brickschema.org.schema._1_0_2.Brick.IHeat_Exchanger_Supply_Water_Temperature_Sensor;  
import brickschema.org.schema._1_0_2.Brick.IHeat_Exchanger_Discharge_Water_Temperature_Sensor;  


public interface IHWS_Heat_Exchanger_Discharge_Water_Temperature_Sensor extends ISupply_Water_Temperature_Sensor, IHeat_Exchanger_Supply_Water_Temperature_Sensor, IHeat_Exchanger_Discharge_Water_Temperature_Sensor {


	public IRI iri();
			
	
}
