/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package brickschema.org.schema._1_0_2.Brick;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import brickschema.org.schema._1_0_2.Brick.IHWS_Supply_Water_Temperature_Setpoint;  
import brickschema.org.schema._1_0_2.Brick.IMedium_Temperature_Hot_Water_Discharge_Temperature_High_Reset_Setpoint;  
import brickschema.org.schema._1_0_2.Brick.IMedium_Temperature_Hot_Water_Supply_Temperature_High_Reset_Setpoint;  
import brickschema.org.schema._1_0_2.Brick.IHWS_Discharge_Water_Temperature_Setpoint;  
import brickschema.org.schema._1_0_2.Brick.IHot_Water_Supply_Temperature_High_Reset_Setpoint;  


public interface IHWS_Medium_Temperature_Hot_Water_Discharge_Temperature_High_Reset_Setpoint extends IHWS_Supply_Water_Temperature_Setpoint, IMedium_Temperature_Hot_Water_Discharge_Temperature_High_Reset_Setpoint, IMedium_Temperature_Hot_Water_Supply_Temperature_High_Reset_Setpoint, IHWS_Discharge_Water_Temperature_Setpoint, IHot_Water_Supply_Temperature_High_Reset_Setpoint {


	public IRI iri();
			
	
}
