/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package brickschema.org.schema._1_0_2.Brick;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import brickschema.org.schema._1_0_2.Brick.IOpen_Heating_Valve_Outside_Air_Temperature_Setpoint;  


public interface IHWS_Open_Heating_Valve_Outside_Air_Temperature_Setpoint extends IOpen_Heating_Valve_Outside_Air_Temperature_Setpoint {


	public IRI iri();
			
	
}
