/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package brickschema.org.schema._1_0_2.Brick;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import brickschema.org.schema._1_0_2.Brick.IHot_Water_Supply_Temperature_Sensor;  
import brickschema.org.schema._1_0_2.Brick.IMedium_Temperature_Hot_Water_Supply_Temperature_Sensor;  
import brickschema.org.schema._1_0_2.Brick.IHWS_Hot_Water_Supply_Temperature_Sensor;  
import brickschema.org.schema._1_0_2.Brick.IMedium_Temperature_Hot_Water_Discharge_Temperature_Sensor;  
import brickschema.org.schema._1_0_2.Brick.IHWS_Hot_Water_Discharge_Temperature_Sensor;  


public interface IHWS_Medium_Temperature_Hot_Water_Supply_Temperature_Sensor extends IHot_Water_Supply_Temperature_Sensor, IMedium_Temperature_Hot_Water_Supply_Temperature_Sensor, IHWS_Hot_Water_Supply_Temperature_Sensor, IMedium_Temperature_Hot_Water_Discharge_Temperature_Sensor, IHWS_Hot_Water_Discharge_Temperature_Sensor {


	public IRI iri();
			
	
}
