/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package brickschema.org.schema._1_0_2.Brick;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import brickschema.org.schema._1_0_2.Brick.IHWS_Hot_Water_Differential_Pressure_Sensor;  
import brickschema.org.schema._1_0_2.Brick.IMedium_Temperature_Hot_Water_Differential_Pressure_Sensor;  


public interface IHWS_Medium_Temperature_Hot_Water_Differential_Pressure_Sensor extends IHWS_Hot_Water_Differential_Pressure_Sensor, IMedium_Temperature_Hot_Water_Differential_Pressure_Sensor {


	public IRI iri();
			
	
}
