/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package brickschema.org.schema._1_0_2.Brick;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import brickschema.org.schema._1_0_2.Brick.IShutdown_Hot_Water_When_Unoccupied_Command;  


public interface IHWS_Shutdown_Hot_Water_When_Unoccupied_Command extends IShutdown_Hot_Water_When_Unoccupied_Command {


	public IRI iri();
			
	
}
