/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package brickschema.org.schema._1_0_2.Brick;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import brickschema.org.schema._1_0_2.Brick.IHumidity_Setpoint;  
import brickschema.org.schema._1_0_2.Brick.ILow_Humidity_Alarm;  


public interface ILow_Humidity_Alarm_Setpoint extends IHumidity_Setpoint, ILow_Humidity_Alarm {


	public IRI iri();
			
	
}
