/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package brickschema.org.schema._1_0_2.Brick;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import brickschema.org.schema._1_0_2.Brick.ILow_Temperature;  
import brickschema.org.schema._1_0_2.Brick.ITemperature_Low;  
import brickschema.org.schema._1_0_2.Brick.IAlarm;  


public interface ILow_Temperature_Alarm extends ILow_Temperature, ITemperature_Low, IAlarm {


	public IRI iri();
			
	
}
