/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package brickschema.org.schema._1_0_2.Brick;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import brickschema.org.schema._1_0_2.Brick.IHot_Water_Supply_Temperature_Low_Reset_Setpoint;  
import brickschema.org.schema._1_0_2.Brick.IMedium_Temperature_Hot_Water;  
import brickschema.org.schema._1_0_2.Brick.IDischarge_Water_Temperature_Setpoint;  


public interface IMedium_Temperature_Hot_Water_Discharge_Temperature_Low_Reset_Setpoint extends IHot_Water_Supply_Temperature_Low_Reset_Setpoint, IMedium_Temperature_Hot_Water, IDischarge_Water_Temperature_Setpoint {


	public IRI iri();
			
	
}
