/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package brickschema.org.schema._1_0_2.Brick;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import brickschema.org.schema._1_0_2.Brick.ILow_Temperature;  
import brickschema.org.schema._1_0_2.Brick.IMedium_Temperature_Hot_Water_Supply_Temperature;  
import brickschema.org.schema._1_0_2.Brick.ITemperature_Low;  


public interface IMedium_Temperature_Hot_Water_Supply_Temperature_Low_Reset extends ILow_Temperature, IMedium_Temperature_Hot_Water_Supply_Temperature, ITemperature_Low {


	public IRI iri();
			
	
}
