/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package brickschema.org.schema._1_0_2.Brick;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import brickschema.org.schema._1_0_2.Brick.ISupply_Water_Temperature;  
import brickschema.org.schema._1_0_2.Brick.IMedium_Temperature_Hot_Water;  
import brickschema.org.schema._1_0_2.Brick.IWater_Supply_Temperature;  


public interface IMedium_Temperature_Hot_Water_Supply_Temperature extends ISupply_Water_Temperature, IMedium_Temperature_Hot_Water, IWater_Supply_Temperature {


	public IRI iri();
			
	
}
