/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package brickschema.org.schema._1_0_2.Brick;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import brickschema.org.schema._1_0_2.Brick.IHigh_Temperature_Hot_Water_Discharge_Temperature;  
import brickschema.org.schema._1_0_2.Brick.IMedium_Temperature_Hot_Water_Discharge_Temperature;  


public interface IMedium_Temperature_Hot_Water_Discharge_Temperature_High_Reset extends IHigh_Temperature_Hot_Water_Discharge_Temperature, IMedium_Temperature_Hot_Water_Discharge_Temperature {


	public IRI iri();
			
	
}
