/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package brickschema.org.schema._1_0_2.Brick;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import brickschema.org.schema._1_0_2.Brick.IMedium_Temperature_Hot_Water;  
import brickschema.org.schema._1_0_2.Brick.IDifferential_Pressure_Load_Shed_Status;  


public interface IMedium_Temperature_Hot_Water_Supply_Temperature_Load_Shed_Status extends IMedium_Temperature_Hot_Water, IDifferential_Pressure_Load_Shed_Status {


	public IRI iri();
			
	
}
