/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package brickschema.org.schema._1_0_2.Brick;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import brickschema.org.schema._1_0_2.Brick.IHot_Water_Differential_Pressure_Setpoint;  
import brickschema.org.schema._1_0_2.Brick.ILoad_Shed_Differential_Pressure_Setpoint;  
import brickschema.org.schema._1_0_2.Brick.IMedium_Temperature_Hot_Water;  
import brickschema.org.schema._1_0_2.Brick.ITemperature_Setpoint;  


public interface IMedium_Temperature_Hot_Water_Differential_Pressure_Load_Shed_Setpoint extends IHot_Water_Differential_Pressure_Setpoint, ILoad_Shed_Differential_Pressure_Setpoint, IMedium_Temperature_Hot_Water, ITemperature_Setpoint {


	public IRI iri();
			
	
}
