/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package brickschema.org.schema._1_0_2.Brick;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import brickschema.org.schema._1_0_2.Brick.ICooling_Discharge_Air_Flow_Setpoint;  
import brickschema.org.schema._1_0_2.Brick.ISupply_Air_Flow_Setpoint;  


public interface IOccupied_Cooling_Discharge_Air_Flow_Setpoint extends ICooling_Discharge_Air_Flow_Setpoint, ISupply_Air_Flow_Setpoint {


	public IRI iri();
			
	
}
