/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package brickschema.org.schema._1_0_2.Brick;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import brickschema.org.schema._1_0_2.Brick.IOutside_Air;  
import brickschema.org.schema._1_0_2.Brick.IAir_Flow_Setpoint;  


public interface IOutside_Min_Air_Flow_Setpoint extends IOutside_Air, IAir_Flow_Setpoint {


	public IRI iri();
			
	
}
