/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package brickschema.org.schema._1_0_2.Brick;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import brickschema.org.schema._1_0_2.Brick.IDamper_Command;  
import brickschema.org.schema._1_0_2.Brick.IOutside_Air;  


public interface IOutside_Air_Damper_Position_Command extends IDamper_Command, IOutside_Air {


	public IRI iri();
			
	
}
