/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package brickschema.org.schema._1_0_2.Brick;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import brickschema.org.schema._1_0_2.Brick.IOutside_Air;  
import brickschema.org.schema._1_0_2.Brick.IHumidity_Sensor;  


public interface IOutside_Air_Humidity_Sensor extends IOutside_Air, IHumidity_Sensor {


	public IRI iri();
			
	
}
