/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package brickschema.org.schema._1_0_2.Brick;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import brickschema.org.schema._1_0_2.Brick.ICO2_Sensor;  
import brickschema.org.schema._1_0_2.Brick.IOutside_Air;  


public interface IOutside_Air_CO2_Sensor extends ICO2_Sensor, IOutside_Air {


	public IRI iri();
			
	
}
