/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package brickschema.org.schema._1_0_2.Brick;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import brickschema.org.schema._1_0_2.Brick.IDischarge_Fan;  
import brickschema.org.schema._1_0_2.Brick.IReturn_Fan_Differential_Speed;  


public interface IReturn_Discharge_Fan_Differential_Speed extends IDischarge_Fan, IReturn_Fan_Differential_Speed {


	public IRI iri();
			
	
}
