/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package brickschema.org.schema._1_0_2.Brick;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import brickschema.org.schema._1_0_2.Brick.IHigh_Temperature_Alarm;  
import brickschema.org.schema._1_0_2.Brick.IReturn_Air;  


public interface IReturn_Air_Temperature_High_Limit_Alarm extends IHigh_Temperature_Alarm, IReturn_Air {


	public IRI iri();
			
	
}
