/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package brickschema.org.schema._1_0_2.Brick;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import brickschema.org.schema._1_0_2.Brick.IReturn_Air;  
import brickschema.org.schema._1_0_2.Brick.IDewpoint_Sensor;  


public interface IReturn_Air_Dewpoint_Sensor extends IReturn_Air, IDewpoint_Sensor {


	public IRI iri();
			
	
}
