/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package brickschema.org.schema._1_0_2.Brick;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import brickschema.org.schema._1_0_2.Brick.IFan_Air_Flow_Sensor;  


public interface IReturn_Fan_Fan_Air_Flow_Sensor extends IFan_Air_Flow_Sensor {


	public IRI iri();
			
	
}
