/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package brickschema.org.schema._1_0_2.Brick;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import brickschema.org.schema._1_0_2.Brick.IRun_Status;  
import brickschema.org.schema._1_0_2.Brick.IEnable_Status;  


public interface IRun_Enable_Status extends IRun_Status, IEnable_Status {


	public IRI iri();
			
	
}
