/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package brickschema.org.schema._1_0_2.Brick;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import brickschema.org.schema._1_0_2.Brick.IPV_Current_Output_Sensor;  
import brickschema.org.schema._1_0_2.Brick.IPhotovoltaic_Current_Output_Sensor;  


public interface ISolar_Panel_Photovoltaic_Current_Output_Sensor extends IPV_Current_Output_Sensor, IPhotovoltaic_Current_Output_Sensor {


	public IRI iri();
			
	
}
