/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package brickschema.org.schema._1_0_2.Brick;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import brickschema.org.schema._1_0_2.Brick.IOn_Off_Command;  
import brickschema.org.schema._1_0_2.Brick.ISteam;  


public interface ISteam_On_Off_Command extends IOn_Off_Command, ISteam {


	public IRI iri();
			
	
}
