/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package brickschema.org.schema._1_0_2.Brick;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import brickschema.org.schema._1_0_2.Brick.ISupply_Air_Temperature;  
import brickschema.org.schema._1_0_2.Brick.IHeating_Temperature;  


public interface ISupply_Air_Temperature_Heating extends ISupply_Air_Temperature, IHeating_Temperature {


	public IRI iri();
			
	
}
