/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package brickschema.org.schema._1_0_2.Brick;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import brickschema.org.schema._1_0_2.Brick.ICooling_Coil_Valve_Pressure_Sensor;  


public interface ISupply_Fan_Cooling_Coil_Valve_Pressure_Sensor extends ICooling_Coil_Valve_Pressure_Sensor {


	public IRI iri();
			
	
}
