/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package brickschema.org.schema._1_0_2.Brick;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import brickschema.org.schema._1_0_2.Brick.ISupply_Air;  
import brickschema.org.schema._1_0_2.Brick.ISmoke_Detected;  


public interface ISupply_Air_Smoke_Detected extends ISupply_Air, ISmoke_Detected {


	public IRI iri();
			
	
}
