/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package brickschema.org.schema._1_0_2.Brick;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import brickschema.org.schema._1_0_2.Brick.IDischarge_Air;  
import brickschema.org.schema._1_0_2.Brick.IPressure_Status;  
import brickschema.org.schema._1_0_2.Brick.ISupply_Air;  


public interface ISupply_Air_Duct_Pressure_Status extends IDischarge_Air, IPressure_Status, ISupply_Air {


	public IRI iri();
			
	
}
