/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package brickschema.org.schema._1_0_2.Brick;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import brickschema.org.schema._1_0_2.Brick.ISupply_Air_Temperature_Setpoint;  
import brickschema.org.schema._1_0_2.Brick.ITemperature_Differential_Reset_Setpoint;  
import brickschema.org.schema._1_0_2.Brick.IDischarge_Air_Temperature_Setpoint;  


public interface ISupply_Air_Temperature_Reset_Differential_Setpoint extends ISupply_Air_Temperature_Setpoint, ITemperature_Differential_Reset_Setpoint, IDischarge_Air_Temperature_Setpoint {


	public IRI iri();
			
	
}
