/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package brickschema.org.schema._1_0_2.Brick;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import brickschema.org.schema._1_0_2.Brick.ISupply_Water_Differential_Pressure_Integral_Time_Setpoint;  


public interface IThermal_Energy_Storage_Supply_Water_Differential_Pressure_Integral_Time_Setpoint extends ISupply_Water_Differential_Pressure_Integral_Time_Setpoint {


	public IRI iri();
			
	
}
