/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package brickschema.org.schema._1_0_2.Brick;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import brickschema.org.schema._1_0_2.Brick.ITemperature_High_Limit_Setpoint;  


public interface IThumbwheel_Temperature_High_Limit_Setpoint extends ITemperature_High_Limit_Setpoint {


	public IRI iri();
			
	
}
