/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package brickschema.org.schema._1_0_2.Brick;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import brickschema.org.schema._1_0_2.Brick.ICooling;  
import brickschema.org.schema._1_0_2.Brick.ISupply_Air_Flow;  


public interface IUnoccupied_Cooling_Supply_Air_Flow extends ICooling, ISupply_Air_Flow {


	public IRI iri();
			
	
}
