/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package brickschema.org.schema._1_0_2.Brick;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import brickschema.org.schema._1_0_2.Brick.IVAV_Occupied_Cooling_Temperature_Setpoint;  
import brickschema.org.schema._1_0_2.Brick.IOccupied_Cooling_Temperature_Dead_Band_Setpoint;  
import brickschema.org.schema._1_0_2.Brick.IZone_Cooling_Temperature_Dead_Band_Setpoint;  


public interface IVAV_Occupied_Cooling_Temperature_Dead_Band_Setpoint extends IVAV_Occupied_Cooling_Temperature_Setpoint, IOccupied_Cooling_Temperature_Dead_Band_Setpoint, IZone_Cooling_Temperature_Dead_Band_Setpoint {


	public IRI iri();
			
	
}
