/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package brickschema.org.schema._1_0_2.Brick;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import brickschema.org.schema._1_0_2.Brick.IDamper_Position_Setpoint;  
import brickschema.org.schema._1_0_2.Brick.IOutside_Air_Damper_Close_Limit_Setpoint;  


public interface IVAV_Outside_Air_Damper_Close_Limit_Setpoint extends IDamper_Position_Setpoint, IOutside_Air_Damper_Close_Limit_Setpoint {


	public IRI iri();
			
	
}
