/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package brickschema.org.schema._1_0_2.Brick;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import brickschema.org.schema._1_0_2.Brick.IDischarge_Air_Duct_Pressure_Status;  
import brickschema.org.schema._1_0_2.Brick.ISupply_Air_Duct_Pressure_Status;  


public interface IVAV_Discharge_Air_Duct_Pressure_Status extends IDischarge_Air_Duct_Pressure_Status, ISupply_Air_Duct_Pressure_Status {


	public IRI iri();
			
	
}
