/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package brickschema.org.schema._1_0_2.Brick;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import brickschema.org.schema._1_0_2.Brick.IHeating_Max_Discharge_Air_Flow_Setpoint;  
import brickschema.org.schema._1_0_2.Brick.IHeating_Discharge_Air_Flow_Setpoint;  
import brickschema.org.schema._1_0_2.Brick.IVAV_Heating_Supply_Air_Flow_Setpoint;  
import brickschema.org.schema._1_0_2.Brick.IVAV_Heating_Discharge_Air_Flow_Setpoint;  
import brickschema.org.schema._1_0_2.Brick.IHeating_Max_Supply_Air_Flow_Setpoint;  


public interface IVAV_Heating_Max_Supply_Air_Flow_Setpoint extends IHeating_Max_Discharge_Air_Flow_Setpoint, IHeating_Discharge_Air_Flow_Setpoint, IVAV_Heating_Supply_Air_Flow_Setpoint, IVAV_Heating_Discharge_Air_Flow_Setpoint, IHeating_Max_Supply_Air_Flow_Setpoint {


	public IRI iri();
			
	
}
