/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package brickschema.org.schema._1_0_2.Brick;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import brickschema.org.schema._1_0_2.Brick.ICO2_Level_Sensor;  
import brickschema.org.schema._1_0_2.Brick.IVAV_CO2_Sensor;  


public interface IVAV_CO2_Level_Sensor extends ICO2_Level_Sensor, IVAV_CO2_Sensor {


	public IRI iri();
			
	
}
