/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package brickschema.org.schema._1_0_2.Brick;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import brickschema.org.schema._1_0_2.Brick.IDischarge_Air_Flow_Command;  
import brickschema.org.schema._1_0_2.Brick.ISupply_Air_Flow_Command;  


public interface IVAV_Discharge_Air_Flow_Command extends IDischarge_Air_Flow_Command, ISupply_Air_Flow_Command {


	public IRI iri();
			
	
}
