/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package brickschema.org.schema._1_0_2.Brick;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import brickschema.org.schema._1_0_2.Brick.IBooster_Fan_Start_Stop_Command;  
import brickschema.org.schema._1_0_2.Brick.IVAV_Booster_Fan_Command;  


public interface IVAV_Booster_Fan_Start_Stop_Command extends IBooster_Fan_Start_Stop_Command, IVAV_Booster_Fan_Command {


	public IRI iri();
			
	
}
