/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package brickschema.org.schema._1_0_2.Brick;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import brickschema.org.schema._1_0_2.Brick.ITemporary_Occupancy_Status;  
import brickschema.org.schema._1_0_2.Brick.IVAV_Occupancy_Status;  


public interface IVAV_Temporary_Occupancy_Status extends ITemporary_Occupancy_Status, IVAV_Occupancy_Status {


	public IRI iri();
			
	
}
