/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package brickschema.org.schema._1_0_2.Brick;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import brickschema.org.schema._1_0_2.Brick.IUndefinedMeasurement;  
import brickschema.org.schema._1_0_2.Brick.IPressure_Setpoint;  


public interface IVelocity_Pressure_Setpoint extends IUndefinedMeasurement, IPressure_Setpoint {


	public IRI iri();
			
	
}
