/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package brickschema.org.schema._1_0_2.Brick;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import brickschema.org.schema._1_0_2.Brick.IVFD_Status;  
import brickschema.org.schema._1_0_2.Brick.IMotor_Direction_Status;  


public interface IVFD_Motor_Direction_Status extends IVFD_Status, IMotor_Direction_Status {


	public IRI iri();
			
	
}
