/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package brickschema.org.schema._1_0_2.Brick;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import brickschema.org.schema._1_0_2.Brick.IVFD_Frequency_Command;  
import brickschema.org.schema._1_0_2.Brick.IMax_Frequency_Command;  


public interface IVFD_Max_Frequency_Command extends IVFD_Frequency_Command, IMax_Frequency_Command {


	public IRI iri();
			
	
}
