/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package brickschema.org.schema._1_0_2.Brick;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import brickschema.org.schema._1_0_2.Brick.IVFD_Status;  
import brickschema.org.schema._1_0_2.Brick.IHand_Auto_Status;  
import brickschema.org.schema._1_0_2.Brick.IManual_Auto_Status;  


public interface IVFD_Hand_Auto_Status extends IVFD_Status, IHand_Auto_Status, IManual_Auto_Status {


	public IRI iri();
			
	
}
