/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package brickschema.org.schema._1_0_2.Brick;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import brickschema.org.schema._1_0_2.Brick.IVFD_Alarm;  
import brickschema.org.schema._1_0_2.Brick.IMaintenance_Required_Alarm;  


public interface IVFD_Maintenance_Required_Alarm extends IVFD_Alarm, IMaintenance_Required_Alarm {


	public IRI iri();
			
	
}
