/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package brickschema.org.schema._1_0_2.Brick;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import brickschema.org.schema._1_0_2.Brick.IMotor_Start_Stop_Status;  
import brickschema.org.schema._1_0_2.Brick.IVFD_Start_Stop_Status;  


public interface IVFD_Motor_Start_Stop_Status extends IMotor_Start_Stop_Status, IVFD_Start_Stop_Status {


	public IRI iri();
			
	
}
