/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package brickschema.org.schema._1_0_2.Brick;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import brickschema.org.schema._1_0_2.Brick.IRun_Enable_Command;  
import brickschema.org.schema._1_0_2.Brick.IVFD_Enable_Command;  


public interface IVFD_Run_Enable_Command extends IRun_Enable_Command, IVFD_Enable_Command {


	public IRI iri();
			
	
}
