/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package brickschema.org.schema._1_0_2.Brick;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import brickschema.org.schema._1_0_2.Brick.IRun_Enable_Status;  
import brickschema.org.schema._1_0_2.Brick.IVFD_Run_Status;  


public interface IVFD_Run_Enable_Status extends IRun_Enable_Status, IVFD_Run_Status {


	public IRI iri();
			
	
}
