/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package brickschema.org.schema._1_0_2.Brick;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import brickschema.org.schema._1_0_2.Brick.ICooling_Tower_Fan_Speed_Setpoint;  


public interface IWater_System_Cooling_Tower_Fan_Speed_Setpoint extends ICooling_Tower_Fan_Speed_Setpoint {


	public IRI iri();
			
	
}
