/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package brickschema.org.schema._1_0_2.Brick;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import brickschema.org.schema._1_0_2.Brick.IDeionised_Water_Conductivity_Sensor;  


public interface IWater_System_Deionised_Water_Conductivity_Sensor extends IDeionised_Water_Conductivity_Sensor {


	public IRI iri();
			
	
}
