/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package brickschema.org.schema._1_0_2.Brick;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import brickschema.org.schema._1_0_2.Brick.IWater_System_Pump_Status;  
import brickschema.org.schema._1_0_2.Brick.IPump_Start_Stop_Status;  


public interface IWater_System_Pump_Start_Stop_Status extends IWater_System_Pump_Status, IPump_Start_Stop_Status {


	public IRI iri();
			
	
}
