/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package brickschema.org.schema._1_0_2.Brick;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import brickschema.org.schema._1_0_2.Brick.IWeather_Rain_Sensor;  
import brickschema.org.schema._1_0_2.Brick.IRain_Duration_Sensor;  


public interface IWeather_Rain_Duration_Sensor extends IWeather_Rain_Sensor, IRain_Duration_Sensor {


	public IRI iri();
			
	
}
