/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package brickschema.org.schema._1_0_2.Brick;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import brickschema.org.schema._1_0_2.Brick.ISolar_Radiance_Sensor;  


public interface IWeather_Solar_Radiance_Sensor extends ISolar_Radiance_Sensor {


	public IRI iri();
			
	
}
