from rdflib import Namespace, Graph, Literal, RDF, URIRef
from rdfalchemy.rdfSubject import rdfSubject
from rdfalchemy import rdfSingle, rdfMultiple, rdfList

from brick.brickschema.org.schema._1_0_2.Brick.HWS_Supply_Water_Temperature_Setpoint import HWS_Supply_Water_Temperature_Setpoint
from brick.brickschema.org.schema._1_0_2.Brick.Medium_Temperature_Hot_Water_Discharge_Temperature_High_Reset_Setpoint import Medium_Temperature_Hot_Water_Discharge_Temperature_High_Reset_Setpoint
from brick.brickschema.org.schema._1_0_2.Brick.Medium_Temperature_Hot_Water_Supply_Temperature_High_Reset_Setpoint import Medium_Temperature_Hot_Water_Supply_Temperature_High_Reset_Setpoint
from brick.brickschema.org.schema._1_0_2.Brick.HWS_Discharge_Water_Temperature_Setpoint import HWS_Discharge_Water_Temperature_Setpoint
from brick.brickschema.org.schema._1_0_2.Brick.Hot_Water_Supply_Temperature_High_Reset_Setpoint import Hot_Water_Supply_Temperature_High_Reset_Setpoint


class HWS_Medium_Temperature_Hot_Water_Discharge_Temperature_High_Reset_Setpoint(HWS_Supply_Water_Temperature_Setpoint,Medium_Temperature_Hot_Water_Discharge_Temperature_High_Reset_Setpoint,Medium_Temperature_Hot_Water_Supply_Temperature_High_Reset_Setpoint,HWS_Discharge_Water_Temperature_Setpoint,Hot_Water_Supply_Temperature_High_Reset_Setpoint):
    rdf_type = Namespace('https://brickschema.org/schema/1.0.2/Brick#').HWS_Medium_Temperature_Hot_Water_Discharge_Temperature_High_Reset_Setpoint
	
	
