from rdflib import Namespace, Graph, Literal, RDF, URIRef
from rdfalchemy.rdfSubject import rdfSubject
from rdfalchemy import rdfSingle, rdfMultiple, rdfList

from brick.brickschema.org.schema._1_0_2.Brick.Occupied_Cooling_Discharge_Air_Flow_Setpoint import Occupied_Cooling_Discharge_Air_Flow_Setpoint
from brick.brickschema.org.schema._1_0_2.Brick.Occupied_Cooling_Supply_Air_Flow_Setpoint import Occupied_Cooling_Supply_Air_Flow_Setpoint
from brick.brickschema.org.schema._1_0_2.Brick.Cooling_Max_Supply_Air_Flow_Setpoint import Cooling_Max_Supply_Air_Flow_Setpoint
from brick.brickschema.org.schema._1_0_2.Brick.Cooling_Max_Discharge_Air_Flow_Setpoint import Cooling_Max_Discharge_Air_Flow_Setpoint


class Occupied_Cooling_Max_Supply_Air_Flow_Setpoint(Occupied_Cooling_Discharge_Air_Flow_Setpoint,Occupied_Cooling_Supply_Air_Flow_Setpoint,Cooling_Max_Supply_Air_Flow_Setpoint,Cooling_Max_Discharge_Air_Flow_Setpoint):
    rdf_type = Namespace('https://brickschema.org/schema/1.0.2/Brick#').Occupied_Cooling_Max_Supply_Air_Flow_Setpoint
	
	
